<?php
/**
 * @var \Fooman\PdfCustomiser\Block\Table\BundleExtras $block
 */

$orderItem = $block->getOrderItem();
$item = $block->getItem();
$parentQty = $item->getQty() ? $item->getQty() : $item->getQtyOrdered();
$productOptions = $orderItem->getProductOptions();
?>

<?php if (isset($productOptions['bundle_options'])) : ?>
    <?php $bundleOptions = $productOptions['bundle_options']; ?>
    <?php uasort(
        $bundleOptions,
        function ($a, $b) {
            return $a['option_id'] > $b['option_id'];
        }
    ); ?>
    <?php foreach ($bundleOptions as $bundleOption) :;?>
        <br/><?php echo $block->escapeHtml($bundleOption['label']) ?> <br/>
        <?php foreach ($bundleOption['value'] as $value):?>
            <b>&nbsp;&nbsp;&nbsp;&nbsp; <?php echo __('Title:') ?> </b>
            <?php echo $block->escapeHtml($value['title']) ?><br/>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif; ?>
