<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_invoice = $block->getInvoice() ?>
<?php $_order   = $block->getOrder() ?>
<?php if ($_invoice && $_order): ?>
     <table class="email-items" width="650">
        <thead>
            <tr>
                <th class="item-info" align="left" bgcolor="#EAEAEA" style="font-size: 13px;padding: 5px 9px 6px 9px;line-height: 1em;">
                    <?= /* @escapeNotVerified */  __('Items') ?>
                </th>
                <th class="item-qty" align="left" bgcolor="#EAEAEA" style="font-size: 13px;padding: 5px 9px 6px 9px;line-height: 1em;">
                    <?= /* @escapeNotVerified */  __('Sku') ?>
                </th>
                <th class="item-qty" align="center" bgcolor="#EAEAEA" style="font-size: 13px;padding: 5px 9px 6px 9px;line-height: 1em;">
                    <?= /* @escapeNotVerified */  __('Qty') ?>
                </th>
                <th class="item-price" align="right" bgcolor="#EAEAEA" style="font-size: 13px;padding: 5px 9px 6px 9px;line-height: 1em;">
                    <?= /* @escapeNotVerified */  __('Subtotal') ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_invoice->getAllItems() as $_item): ?>
            <?php
                if ($_item->getOrderItem()->getParentItem()) {
                    continue;
                }
            ?>
            <tbody bgcolor="#F6F6F6">
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('invoice_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
