<?php
/**
 * @var \Fooman\PdfCustomiser\Block\Invoice $block
 */
?>
<?php $invoice = $block->getInvoice() ?>
<?php $order = $block->getOrder() ?>
<?php $design = $block->getDesign() ?>

<table width="100%" border="0" cellpadding="8" cellspacing="0">
    <tr>
        <?php if ($block->isLogoOnRight()): ?>
            <td
                    valign="top"
                    width="50%"
                    height="10mm"
                    style="font-weight:bold;
                    font-size:<?php echo $block->getFontsize('large') ?>"><?php echo $block->escapeHtml($block->getTitle()) ?></td>
            <td valign="top">&nbsp;<?php echo $block->getLogoBlock() ?></td>
        <?php else: ?>
            <td width="50%"
                valign="top">&nbsp;<?php echo $block->getLogoBlock() ?></td>
            <td
                    valign="top"
                    height="10mm"
                    style="font-weight:bold;
                    font-size:<?php echo $block->getFontsize('large') ?>"><?php echo $block->escapeHtml($block->getTitle()) ?></td>
        <?php endif; ?>
    </tr>
    <tr>
        <td valign="top" width="50%"><?php echo __('Invoice #') ?>: <?php echo $invoice->getIncrementId() ?><br/>
            <?php echo __('Invoice Date') ?>: <?php echo $block->getFormattedDate($invoice->getCreatedAt()) ?><br/>
            <?php if ($block->showOrderIncrementId()): ?>
                <?php echo __('Order #') . ': ' . $order->getIncrementId() ?><br/>
            <?php endif; ?>
            <?php echo __('Order Date') ?>: <?php echo $order->getCreatedAt() ?>
        </td>
        <td valign="top"><?php echo nl2br($block->escapeHtml($block->getOwnerAddress())) ?></td>
    </tr>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
        <?php if ($block->shouldDisplayBothAddresses()): ?>
        <!--Example with indentation of address, adjust the percentages to adjust the left-right positioning
            <td valign="top" colspan="2">
                <table>
                    <tr>
                        <td width="5%"></td>
                        <td width="45%"><?php echo __('Sold to:') ?><br/><?php echo $block->getBillingAddress() ?></td>
                        <td width="5%"></td>
                        <td width="45%"><?php echo __('Ship to:') ?><br/><?php echo $block->getShippingAddress() ?></td>
                    </tr>
                </table>
            </td>-->
        <td valign="top" width="50%" style="font-weight:bold;border: 2px solid #808080;background-color: #ededed"><?php echo __('Sold to:') ?></td>
        <td valign="top" style="font-weight:bold;border: 2px solid #808080;background-color: #ededed"><?php if (!$order->getIsVirtual()): ?><?php echo __('Deliver to:') ?><?php endif; ?></td>
    </tr>
    <tr>
        <td valign="top" style="border-left: 2px solid #808080;border-bottom: 2px solid #808080;"><?php echo $block->getBillingAddress() ?></td>
        <td valign="top" style="border-bottom: 2px solid #808080;border-right: 2px solid #808080;"><?php if (!$order->getIsVirtual()): ?><?php echo $block->getShippingAddress() ?><?php endif; ?></td>

        <?php elseif ($block->shouldDisplayShippingAddress()): ?>
            <td valign="top" colspan="2" style="border-left: 2px solid #808080;border-bottom: 2px solid #808080;border-right: 2px solid #808080;"><?php echo $block->getShippingAddress() ?></td>
        <?php elseif ($block->shouldDisplayBillingAddress()): ?>
            <td valign="top" colspan="2" style="border-left: 2px solid #808080;border-bottom: 2px solid #808080;border-right: 2px solid #808080;"><?php echo $block->getBillingAddress() ?></td>
        <?php endif; ?>
    </tr>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
    <?php if ($order->getIsVirtual()): ?>
        <tr>
            <td valign="top" colspan="2" style="font-weight:bold;border: 2px solid #808080;background-color: #ededed"><strong><?php echo __('Payment Method') ?></strong></td>
        </tr>
        <tr>
            <td valign="top" colspan="2" style="border-left: 2px solid #808080;border-bottom: 2px solid #808080;border-right: 2px solid #808080;"><?php echo $block->getPaymentBlock() ?></td>
        </tr>
    <?php else: ?>
        <tr>
            <td valign="top" width="50%" style="font-weight:bold;border: 2px solid #808080;background-color: #ededed"><strong><?php echo __('Payment Method') ?></strong></td>
            <td valign="top" style="font-weight:bold;border: 2px solid #808080;background-color: #ededed"><strong><?php echo __('Delivery Method') ?></strong></td>
        </tr>
        <tr>
            <td valign="top" width="50%" style="border-left: 2px solid #808080;border-bottom: 2px solid #808080;"><?php echo $block->getPaymentBlock() ?></td>
            <td valign="top" style="border-bottom: 2px solid #808080;border-right: 2px solid #808080;"><?php echo $block->getShippingBlock() ?></td>
        </tr>
    <?php endif; ?>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
    <?php if ($order->getOscOrderComment()): ?>
        <tr>
            <td valign="top"
                width="100%"
                style="<?= /* @noEscape */ $block->getDesign()->getHeaderStyle(true, true)?>"
            ><strong><?= $block->escapeHtml(__('Comment')) ?></strong></td>
        </tr>
        <tr>
            <td valign="top"
                width="100%"
                style="<?= /* @noEscape */ $block->getDesign()->getCellStyle(true, true, true, false)?>"
            ><?= /* @noEscape */ $order->getOscOrderComment() ?></td>
        </tr>
    <?php endif; ?>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
</table>

<?php echo $block->getItemsBlock($design->getItemStyling()) ?>

<?php echo $block->getTotalsBlock() ?>

<?php echo $block->getGiftmessageBlock()?>

<?php echo $block->getTaxTableBlock() ?>

<?php echo $block->getCommentsBlock() ?>

<?php $customText = $block->getCustomText() ?>
<?php if ($customText) : ?>
    <br/>
    <table width="100%" border="0" cellpadding="8" cellspacing="0">
        <tr>
            <td colspan="2"> <?php echo $customText ?></td>
        </tr>
    </table>
<?php endif; ?>
<?php $orderCommant = $block->getOrderCommantBlock() ?>
<?php if ($orderCommant) : ?>
    <br/>
    <strong><?php echo __('Comments') ?></strong><br/> 
    <table width="100%" border="0" cellpadding="8" cellspacing="0">
        <tr>
            <td colspan="2"> <?php echo $orderCommant ?></td>
        </tr>
    </table>
<?php endif; ?>
