<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Reports\Block\Product\Viewed
 */
?>
<?php
if ($exist = ($block->getRecentlyViewedProducts() && $block->getRecentlyViewedProducts()->getSize())) {
    $type = 'widget-viewed';
    $mode = 'grid';

    $type = $type . '-' . $mode;

    $image = 'recently_viewed_products_grid_content_widget';
    $title = __('Recently Viewed');
    $items = $block->getRecentlyViewedProducts();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $rating = 'short';
    $description = ($mode == 'list') ? true : false;
}
?>
<?php if ($exist):?>
<div class="recently_view">
    <h2><?= /* @escapeNotVerified */ $title ?></h2>
    <div class="products list items product-items owl-carousel1 owl-theme">
       <?php foreach ($items as $_item): ?>
        <div class="item product product-item">
           <div class="product-item-info" data-container="product-grid">
              <!--<p class="top_band">Top Rated</p>-->
              <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo" tabindex="-1">
                <span class="product-image-container">
                  <span class="product-image-wrapper">
                      <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                      <span class="image_zoom"></span>
                  </span>
                </span>
              </a>
              <div class="product details product-item-details">
                 <strong class="product name product-item-name">
                 <a class="product-item-divnk" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                   
                  <?php 
                   $productname=$block->escapeHtml($_item->getName());
                   $strlength=strlen($productname);
                  ?>
                  <?php if($strlength<80): ?>

                      <?php /* @escapeNotVerified */ echo $block->escapeHtml($_item->getName());?>

                  <?php else: ?>

                      <?php echo substr($productname,0,75).' ...'; ?>

                  <?php endif; ?>


                 </a>
                 </strong>                                
                 <?php /* @escapeNotVerified */ echo $block->getProductPriceHtml(
                                    $_item,
                                    \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
                                    \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
                                    [
                                        'price_id_suffix' => '-' . $type
                                    ]
                                ) ?>                                                          
                         <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                               <div class="actions-primary">
                                  <?php if ($_item->isSaleable()): ?>
                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                        <button class="action tocart primary"
                                                data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                        </button>
                                    <?php else: ?>
                                        <?php
                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                        ?>
                                        <button class="action tocart primary"
                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                        </button>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php if ($_item->getIsSalable()): ?>
                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                               </div>                                       
                            </div>
                         </div>
              </div>
           </div>
        </div>  
       <?php endforeach ?>                                        
    </div>
</div>
<?php endif;?>
<style type="text/css">
 .recently_view .product-item-info .image_zoom{ position: absolute;right: 16px;bottom: 27px;z-index: 999;}
 .recently_view .product-item a.script-quick-view-button, .products-list .product-item a.script-quick-view-button{opacity: 10 !important;visibility: visible !important;}
 .recently_view a.script-quick-view-button, .products-list a.script-quick-view-button{padding: 33px 32px 26px 49px !important; }
 .recently_view .product-item-info{ float: none; }
 .recently_view .product-image-wrapper{ height: 100%;}
</style>