<div class="recently_view">
    <h2>Recently viewed</h2>
    <div class="products list items product-items owl-carousel1 owl-theme">
        <div class="item product product-item">
           <div class="product-item-info" data-container="product-grid">
              <p class="top_band">Top Rated</p>
              <a href="#" class="product photo product-item-photo" tabindex="-1">
              <span class="product-image-container">
              <span class="product-image-wrapper">
              <img class="product-image-photo img-responsive" src="<?php echo $this->getViewFileUrl('images/product1.jpg'); ?>" alt="Product Name">
              <span class="image_zoom"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/zoom-icon.png'); ?>" alt="Zoom"></span>
            </span>
              </span>
              </a>
              <div class="product details product-item-details">
                 <strong class="product name product-item-name">
                 <a class="product-item-divnk" href="#breathe-easy-tank.html">
                 Linen Look Canvas Fabric - Birds And Butterflies On Natural                           </a>
                 </strong>                                
                 <div class="price-box price-final_price" data-role="priceBox" data-product-id="1817">
                    <span class="price-container price-final_price tax weee">
                    <span id="product-price-1817" data-price-amount="13" data-price-type="finalPrice" class="price-wrapper ">
                    <span class="price">$13.00</span>    </span>
                    </span>
                 </div>                                                           
                 <div class="product-item-inner">
                    <div class="product actions product-item-actions">
                       <div class="actions-primary">
                          <form data-role="tocart-form" action="#checkout/cart/add/uenc/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQvd29tZW4vdG9wcy13b21lbi5odG1s/product/1817/" method="post">
                             <input name="product" value="1817" type="hidden">
                             <input name="uenc" value="aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQvY2hlY2tvdXQvY2FydC9hZGQvdWVuYy9hSFIwY0RvdkwyMWhaMlZ1ZEc4eUxXUmxiVzh1Ym1WNFkyVnpjeTV1WlhRdmQyOXRaVzR2ZEc5d2N5MTNiMjFsYmk1b2RHMXMvcHJvZHVjdC8xODE3Lw,," type="hidden">
                             <input name="form_key" value="V4FMD9Jlh5j4jxFu" type="hidden">                                            <button type="submit" title="Add to Cart" class="action tocart primary">
                             <span>Add to Cart</span>
                             </button>
                             <input class="swatch-input super-attribute-select" name="super_attribute[93]" value="" data-selector="super_attribute[93]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px" type="text"><input class="swatch-input super-attribute-select" name="super_attribute[142]" value="" data-selector="super_attribute[142]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px" type="text">
                          </form>
                       </div>                                       
                    </div>
                 </div>
              </div>
           </div>
        </div>
        <div class="item product product-item">
           <div class="product-item-info" data-container="product-grid">
              <p class="top_band green_band">New</p>
              <a href="#" class="product photo product-item-photo" tabindex="-1">
              <span class="product-image-container">
              <span class="product-image-wrapper">
              <img class="product-image-photo img-responsive" src="<?php echo $this->getViewFileUrl('images/product2.jpg'); ?>" alt="Product Name">
              <span class="image_zoom"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/zoom-icon.png'); ?>" alt="Zoom"></span>
            </span>
              </span>
              </a>
              <div class="product details product-item-details">
                 <strong class="product name product-item-name">
                 <a class="product-item-link" href="#breathe-easy-tank.html">
                 Linen Look Canvas Fabric - Birds And Butterflies On Natural                           </a>
                 </strong>                                
                 <div class="price-box price-final_price" data-role="priceBox" data-product-id="1817">
                    <span class="price-container price-final_price tax weee">
                    <span id="product-price-1817" data-price-amount="13" data-price-type="finalPrice" class="price-wrapper ">
                    <span class="price">$13.00</span>    </span>
                    </span>
                 </div>                                                           
                 <div class="product-item-inner">
                    <div class="product actions product-item-actions">
                       <div class="actions-primary">
                          <form data-role="tocart-form" action="#checkout/cart/add/uenc/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQvd29tZW4vdG9wcy13b21lbi5odG1s/product/1817/" method="post">
                             <input name="product" value="1817" type="hidden">
                             <input name="uenc" value="aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQvY2hlY2tvdXQvY2FydC9hZGQvdWVuYy9hSFIwY0RvdkwyMWhaMlZ1ZEc4eUxXUmxiVzh1Ym1WNFkyVnpjeTV1WlhRdmQyOXRaVzR2ZEc5d2N5MTNiMjFsYmk1b2RHMXMvcHJvZHVjdC8xODE3Lw,," type="hidden">
                             <input name="form_key" value="V4FMD9Jlh5j4jxFu" type="hidden">                                            <button type="submit" title="Add to Cart" class="action tocart primary">
                             <span>Add to Cart</span>
                             </button>
                             <input class="swatch-input super-attribute-select" name="super_attribute[93]" value="" data-selector="super_attribute[93]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px" type="text"><input class="swatch-input super-attribute-select" name="super_attribute[142]" value="" data-selector="super_attribute[142]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px" type="text">
                          </form>
                       </div>                                       
                    </div>
                 </div>
              </div>
           </div>
        </div>
        <div class="item product product-item">
           <div class="product-item-info" data-container="product-grid">
              <p class="top_band">- 50%</p>
              <a href="#" class="product photo product-item-photo" tabindex="-1">
              <span class="product-image-container">
              <span class="product-image-wrapper">
              <img class="product-image-photo img-responsive" src="<?php echo $this->getViewFileUrl('images/product3.jpg'); ?>" alt="Product Name">
              <span class="image_zoom"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/zoom-icon.png'); ?>" alt="Zoom"></span>
            </span>
              </span>
              </a>
              <div class="product details product-item-details">
                 <strong class="product name product-item-name">
                 <a class="product-item-link" href="#breathe-easy-tank.html">
                 Linen Look Canvas Fabric - Birds And Butterflies On Natural                           </a>
                 </strong>                                
                 <div class="price-box price-final_price" data-role="priceBox" data-product-id="1817">
                    <span class="price-container price-final_price tax weee">
                    <span id="product-price-1817" data-price-amount="13" data-price-type="finalPrice" class="price-wrapper ">
                    <span class="price">$13.00</span>    </span>
                    </span>
                 </div>                                                           
                 <div class="product-item-inner">
                    <div class="product actions product-item-actions">
                       <div class="actions-primary">
                          <form data-role="tocart-form" action="#checkout/cart/add/uenc/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQvd29tZW4vdG9wcy13b21lbi5odG1s/product/1817/" method="post">
                             <input name="product" value="1817" type="hidden">
                             <input name="uenc" value="aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQvY2hlY2tvdXQvY2FydC9hZGQvdWVuYy9hSFIwY0RvdkwyMWhaMlZ1ZEc4eUxXUmxiVzh1Ym1WNFkyVnpjeTV1WlhRdmQyOXRaVzR2ZEc5d2N5MTNiMjFsYmk1b2RHMXMvcHJvZHVjdC8xODE3Lw,," type="hidden">
                             <input name="form_key" value="V4FMD9Jlh5j4jxFu" type="hidden">                                            <button type="submit" title="Add to Cart" class="action tocart primary">
                             <span>Add to Cart</span>
                             </button>
                             <input class="swatch-input super-attribute-select" name="super_attribute[93]" value="" data-selector="super_attribute[93]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px" type="text"><input class="swatch-input super-attribute-select" name="super_attribute[142]" value="" data-selector="super_attribute[142]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px" type="text">
                          </form>
                       </div>                                       
                    </div>
                 </div>
              </div>
           </div>
        </div>
        <div class="item product product-item">
           <div class="product-item-info" data-container="product-grid">
              <a href="#" class="product photo product-item-photo" tabindex="-1">
              <span class="product-image-container">
              <span class="product-image-wrapper">
              <img class="product-image-photo img-responsive" src="<?php echo $this->getViewFileUrl('images/product4.jpg'); ?>" alt="Product Name">
              <span class="image_zoom"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/zoom-icon.png'); ?>" alt="Zoom"></span>
            </span>
              </span>
              </a>
              <div class="product details product-item-details">
                 <strong class="product name product-item-name">
                 <a class="product-item-link" href="#breathe-easy-tank.html">
                 Linen Look Canvas Fabric - Birds And Butterflies On Natural                           </a>
                 </strong>                                
                 <div class="price-box price-final_price" data-role="priceBox" data-product-id="1817">
                    <span class="price-container price-final_price tax weee">
                    <span id="product-price-1817" data-price-amount="13" data-price-type="finalPrice" class="price-wrapper ">
                    <span class="price">$13.00</span>    </span>
                    </span>
                 </div>                                                           
                 <div class="product-item-inner">
                    <div class="product actions product-item-actions">
                       <div class="actions-primary">
                          <form data-role="tocart-form" action="#checkout/cart/add/uenc/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQvd29tZW4vdG9wcy13b21lbi5odG1s/product/1817/" method="post">
                             <input name="product" value="1817" type="hidden">
                             <input name="uenc" value="aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQvY2hlY2tvdXQvY2FydC9hZGQvdWVuYy9hSFIwY0RvdkwyMWhaMlZ1ZEc4eUxXUmxiVzh1Ym1WNFkyVnpjeTV1WlhRdmQyOXRaVzR2ZEc5d2N5MTNiMjFsYmk1b2RHMXMvcHJvZHVjdC8xODE3Lw,," type="hidden">
                             <input name="form_key" value="V4FMD9Jlh5j4jxFu" type="hidden">                                            <button type="submit" title="Add to Cart" class="action tocart primary">
                             <span>Add to Cart</span>
                             </button>
                             <input class="swatch-input super-attribute-select" name="super_attribute[93]" value="" data-selector="super_attribute[93]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px" type="text"><input class="swatch-input super-attribute-select" name="super_attribute[142]" value="" data-selector="super_attribute[142]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px" type="text">
                          </form>
                       </div>                                       
                    </div>
                 </div>
              </div>
           </div>
        </div>
        <div class="item product product-item">
           <div class="product-item-info" data-container="product-grid">
              <a href="#" class="product photo product-item-photo" tabindex="-1">
              <span class="product-image-container">
              <span class="product-image-wrapper">
              <img class="product-image-photo img-responsive" src="<?php echo $this->getViewFileUrl('images/product5.jpg'); ?>" alt="Product Name">
              <span class="image_zoom"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/zoom-icon.png'); ?>" alt="Zoom"></span>
            </span>
              </span>
              </a>
              <div class="product details product-item-details">
                 <strong class="product name product-item-name">
                 <a class="product-item-link" href="#breathe-easy-tank.html">
                 Linen Look Canvas Fabric - Birds And Butterflies On Natural                           </a>
                 </strong>                                
                 <div class="price-box price-final_price" data-role="priceBox" data-product-id="1817">
                    <span class="price-container price-final_price tax weee">
                    <span id="product-price-1817" data-price-amount="13" data-price-type="finalPrice" class="price-wrapper ">
                    <span class="price">$13.00</span>    </span>
                    </span>
                 </div>                                                           
                 <div class="product-item-inner">
                    <div class="product actions product-item-actions">
                       <div class="actions-primary">
                          <form data-role="tocart-form" action="#checkout/cart/add/uenc/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQvd29tZW4vdG9wcy13b21lbi5odG1s/product/1817/" method="post">
                             <input name="product" value="1817" type="hidden">
                             <input name="uenc" value="aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQvY2hlY2tvdXQvY2FydC9hZGQvdWVuYy9hSFIwY0RvdkwyMWhaMlZ1ZEc4eUxXUmxiVzh1Ym1WNFkyVnpjeTV1WlhRdmQyOXRaVzR2ZEc5d2N5MTNiMjFsYmk1b2RHMXMvcHJvZHVjdC8xODE3Lw,," type="hidden">
                             <input name="form_key" value="V4FMD9Jlh5j4jxFu" type="hidden">                                            <button type="submit" title="Add to Cart" class="action tocart primary">
                             <span>Add to Cart</span>
                             </button>
                             <input class="swatch-input super-attribute-select" name="super_attribute[93]" value="" data-selector="super_attribute[93]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px" type="text"><input class="swatch-input super-attribute-select" name="super_attribute[142]" value="" data-selector="super_attribute[142]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px" type="text">
                          </form>
                       </div>                                       
                    </div>
                 </div>
              </div>
           </div>
        </div>
        <div class="item product product-item">
           <div class="product-item-info" data-container="product-grid">
              <a href="#" class="product photo product-item-photo" tabindex="-1">
              <span class="product-image-container">
              <span class="product-image-wrapper">
              <img class="product-image-photo img-responsive" src="<?php echo $this->getViewFileUrl('images/product6.jpg'); ?>" alt="Product Name">
              <span class="image_zoom"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/zoom-icon.png'); ?>" alt="Zoom"></span>
            </span>
              </span>
              </a>
              <div class="product details product-item-details">
                 <strong class="product name product-item-name">
                 <a class="product-item-link" href="#breathe-easy-tank.html">
                 Linen Look Canvas Fabric - Birds And Butterflies On Natural                           </a>
                 </strong>                                
                 <div class="price-box price-final_price" data-role="priceBox" data-product-id="1817">
                    <span class="price-container price-final_price tax weee">
                    <span id="product-price-1817" data-price-amount="13" data-price-type="finalPrice" class="price-wrapper ">
                    <span class="price">$13.00</span>    </span>
                    </span>
                 </div>                                                           
                 <div class="product-item-inner">
                    <div class="product actions product-item-actions">
                       <div class="actions-primary">
                          <form data-role="tocart-form" action="#checkout/cart/add/uenc/aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQvd29tZW4vdG9wcy13b21lbi5odG1s/product/1817/" method="post">
                             <input name="product" value="1817" type="hidden">
                             <input name="uenc" value="aHR0cDovL21hZ2VudG8yLWRlbW8ubmV4Y2Vzcy5uZXQvY2hlY2tvdXQvY2FydC9hZGQvdWVuYy9hSFIwY0RvdkwyMWhaMlZ1ZEc4eUxXUmxiVzh1Ym1WNFkyVnpjeTV1WlhRdmQyOXRaVzR2ZEc5d2N5MTNiMjFsYmk1b2RHMXMvcHJvZHVjdC8xODE3Lw,," type="hidden">
                             <input name="form_key" value="V4FMD9Jlh5j4jxFu" type="hidden">                                            <button type="submit" title="Add to Cart" class="action tocart primary">
                             <span>Add to Cart</span>
                             </button>
                             <input class="swatch-input super-attribute-select" name="super_attribute[93]" value="" data-selector="super_attribute[93]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px" type="text"><input class="swatch-input super-attribute-select" name="super_attribute[142]" value="" data-selector="super_attribute[142]" data-validate="{required:true}" aria-required="true" aria-invalid="true" style="visibility: hidden; position:absolute; left:-1000px" type="text">
                          </form>
                       </div>                                       
                    </div>
                 </div>
              </div>
           </div>
        </div>                                          
    </div>
</div>