#! /bin/bash
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/layout/simplegoogleshopping_feeds_showreport.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/layout/simplegoogleshopping_feeds_preview.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/layout/simplegoogleshopping_feeds_index.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/layout/simplegoogleshopping_feeds_edit.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/layout/simplegoogleshopping_feeds_new.xml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/ui_component/cronscheduler_task_listing_2.1.xml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/ui_component/cronscheduler_task_listing_2.0.xml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/ui_component/cronscheduler_job_listing_2.0.xml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/ui_component/cronscheduler_task_listing.xml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/ui_component/cronscheduler_job_listing.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/configuration.phtml
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/addon/selection/active-line.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Tab/Configuration.php
rm ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer/ProcessCronQueueObserver_2.2.8.php
rm ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer/ProcessCronQueueObserver_2.2.7.php
rm ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer/ProcessCronQueueObserver_2.2.6.php
rm ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer/ProcessCronQueueObserver_2.2.5.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode/javascript/javascript.js
rm ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer/ProcessCronQueueObserver_2.0.php
rm ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer/ProcessCronQueueObserver_2.1.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Product/Collection_2.0.php
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/layout/cronscheduler_task_timeline.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Product/Collection_2.1.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/categories.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Product/Collection_2.2.php
rm ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer/ProcessCronQueueObserver_2.2.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/addon/display/autorefresh.js
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task/timeline/actions.phtml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/layout/cronscheduler_task_listing.xml
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/addon/edit/matchbrackets.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode/htmlmixed/htmlmixed.js
rm ./app/code/Wyomind/Core/view/frontend/layout/licensemanager_activation_webservice.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/translate.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Tab/Categories.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Librarysample.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/blackbox.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/utils.js.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Functions/Collection.php
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task/listing/actions.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds/configuration.js
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/layout/cronscheduler_job_listing.xml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/job/listing/actions.phtml
rm ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field/ActivationFlag.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/images/loader-bg-top.gif
rm ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column/Status/Options.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Samplereport.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/filters.phtml
rm ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer/ProcessCronQueueObserver.php
rm ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field/ActivationKey.php
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/[default] en_US.txt
rm ./app/code/Wyomind/Watchlog/view/adminhtml/templates/email/periodical_report.phtml
rm ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field/LicenseStatus.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Tab/Filters.php
rm ./app/code/Wyomind/Watchlog/view/adminhtml/layout/adminhtml_system_config_edit.xml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/web/template/task/grid/status.html
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Product/Collection.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Showreport.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds/categories.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Categories.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/javascript/javascript.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Renderer/Action.php
rm ./app/code/Wyomind/CronScheduler/Ui/Component/JobListing/Column/Group/Options.php
rm ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column/Code/Options.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Renderer/Status.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit/cron.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Feeds/Collection.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css/configuration.css
rm ./app/code/Wyomind/CronScheduler/Ui/Component/JobListing/Column/Code/Options.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/NewAction.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Store/Collection.php
rm ./app/code/Wyomind/Watchlog/view/adminhtml/layout/watchlog_attempts_advanced.xml
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/multiplex/multiplex.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Renderer/Link.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds/blackbox.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Generate.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Tab/Cron.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/htmlmixed/htmlmixed.js
rm ./app/code/Wyomind/Core/view/adminhtml/layout/adminhtml_system_config_edit.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/preview.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Preview.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Updater.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Library.php
rm ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field/Encrypted.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds/filters.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesStockInTheChannel.php
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Job/GenerateSchedule.php
rm ./app/code/Wyomind/Watchlog/view/adminhtml/layout/watchlog_attempts_basic.xml
rm ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column/Messages.php
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task/timeline.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Delete.php
rm ./app/code/Wyomind/Watchlog/Block/Adminhtml/System/Config/Form/Field/Cron.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/email/cron_report.html
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Sample.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode/clike/clike.js
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css/categories.css
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/addon/selection
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode/javascript
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode/htmlmixed
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/images/resize.png
rm ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column/Actions.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Index.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/lib/codemirror.css
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/index.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/images/loader.gif
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds/index.js
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/empty.phtml
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/upgradeToPro.phtml
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/lib/codemirror.js
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds/cron.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Form.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/addon/display
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task/timeline
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Save.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds/Edit.php
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column/Status
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css/blackbox.css
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Tabs.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css/filters.css
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Renderer
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css/preview.css
rm ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Task/Timeline/Actions.php
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/web/template/task/grid
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit/Tab
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/requirejs-config.js
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task/listing
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Functions.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode/css/css.js
rm ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Task/Listing/Actions.php
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/job/listing
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode/php/php.js
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column/Code
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode/xml/xml.js
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates/edit
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task/view.phtml
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Task/MassDelete.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Category/Tree.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Functions
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/matchbrackets.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Preview.php
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/JobListing/Column/Group
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/en_AU.txt
rmdir  ./app/code/Wyomind/Watchlog/Block/Adminhtml/System/Config/Form/Field
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/es_ES.txt
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/it_IT.txt
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/addon/edit
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/TaxClass.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode/clike
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/nl_NL.txt
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/de_DE.txt
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Report.php
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/fr_FR.txt
rm ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Job/Listing/Actions.php
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/JobListing/Column/Code
rm ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies/en_GB.txt
rm ./app/code/Wyomind/Watchlog/Block/Adminhtml/Attempts/Renderer/Status.php
rm ./app/code/Wyomind/CronScheduler/Model/ResourceModel/Task/Collection.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js/feeds
rm ./app/code/Wyomind/Watchlog/Model/ResourceModel/Attempts/Collection.php
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/images/d.png
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/codemirror.css
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/active-line.js
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/javascript
rm ./app/code/Wyomind/Watchlog/view/adminhtml/email/periodical_report.html
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Task/Timeline.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/autorefresh.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/clike/clike.js
rm ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css/cron.css
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/SimpleGoogleShopping.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesCategories.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Product
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/codemirror.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesInventory.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/multiplex
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode/php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode/css
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode/xml
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Grid.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/htmlmixed
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/fullscreen.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Images.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/formatting.js
rm ./app/code/Wyomind/Watchlog/Block/Adminhtml/Attempts/Advanced/Grid.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml/Feeds
rm ./app/code/Wyomind/Watchlog/Controller/Adminhtml/Attempts/Advanced.php
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Task/Listing.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds/Edit.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Feeds.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/mdn-like.css
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/images
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/web/template/task
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Job/Listing.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Feeds/Generate.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Store
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel/Feeds
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form/Field
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/templates
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesDefault.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Console/Command/Generate.php
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing/Column
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/embedded.js
rm ./app/code/Wyomind/Watchlog/Block/Adminhtml/Attempts/Renderer/Ip.php
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/web/css/timeline.css
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Category
rm ./app/code/Wyomind/Watchlog/view/adminhtml/templates/advanced.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Console/Command/Listing.php
rm ./app/code/Wyomind/Watchlog/Controller/Adminhtml/Attempts/Basic.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/addon
rm ./app/code/Wyomind/Watchlog/Block/Adminhtml/Attempts/Basic/Grid.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/php/php.js
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/css/css.js
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/requirejs-config.js
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Task/View.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/Config/UrlRewrite.php
rm ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/xml/xml.js
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesImages.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesPrices.php
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/JobListing/Column
rm ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Task/Timeline.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/css
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/data/Google/Taxonomies
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/task
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/web/js/timeline.js
rm ./app/code/Wyomind/Watchlog/Controller/Adminhtml/History/Purge.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/mode
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/web/css/common.css
rmdir  ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Task/Timeline
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/clike
rmdir  ./app/code/Wyomind/Watchlog/Block/Adminhtml/System/Config/Form
rm ./app/code/Wyomind/CronScheduler/Ui/DataProvider/TaskProvider.php
rmdir  ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Task/Listing
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5/lib
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/templates/job
rm ./app/code/Wyomind/CronScheduler/Block/Adminhtml/UpgradeToPro.php
rm ./app/code/Wyomind/CronScheduler/Console/Command/Task/Listing.php
rmdir  ./app/code/Wyomind/Watchlog/Block/Adminhtml/Attempts/Advanced
rm ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds.php
rmdir  ./app/code/Wyomind/Watchlog/Block/Adminhtml/Attempts/Renderer
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml/Feeds
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web/js
rm ./app/code/Wyomind/Watchlog/Block/Adminhtml/Attempts/Advanced.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/layout
rmdir  ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Job/Listing
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/email
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/adminhtml/routes.xml
rm ./app/code/Wyomind/CronScheduler/Ui/DataProvider/JobProvider.php
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/ui_component
rm ./app/code/Wyomind/Core/Observer/ControllerActionPredispatch.php
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/web/template
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/xml
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/php
rm ./app/code/Wyomind/Core/view/frontend/templates/webservice.phtml
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror/css
rm ./app/code/Wyomind/CronScheduler/Console/Command/Job/Listing.php
rm ./app/code/Wyomind/Watchlog/view/adminhtml/templates/chart.phtml
rm ./app/code/Wyomind/Watchlog/Controller/Adminhtml/Report/Send.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Controller/Adminhtml
rm ./app/code/Wyomind/Watchlog/view/adminhtml/templates/basic.phtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/AttributesUrl.php
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/adminhtml/system.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/CategoryTree.php
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/email_templates.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/Setup/UpgradeSchema.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model/ResourceModel
rm ./app/code/Wyomind/SimpleGoogleShopping/Setup/InstallSchema.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/Requirements.php
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/frontend/routes.xml
rm ./app/code/Wyomind/Watchlog/Block/Adminhtml/Attempts/Basic.php
rm ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Task.php
rm ./app/code/Wyomind/Core/Console/Command/License/InsertCode.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Logger/HandlerCron.php
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System/Config/Form
rm ./app/code/Wyomind/CronScheduler/view/adminhtml/web/js/task.js
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml/web
rm ./app/code/Wyomind/CronScheduler/Console/Command/Task/Show.php
rmdir  ./app/code/Wyomind/Watchlog/Block/Adminhtml/Attempts/Basic
rmdir  ./app/code/Wyomind/Watchlog/view/adminhtml/templates/email
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/adminhtml/menu.xml
rmdir  ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Task
rm ./app/code/Wyomind/Watchlog/Controller/Adminhtml/Attempts.php
rm ./app/code/Wyomind/Core/Console/Command/License/InsertKey.php
rmdir  ./app/code/Wyomind/Watchlog/Controller/Adminhtml/Attempts
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/templates
rm ./app/code/Wyomind/SimpleGoogleShopping/Setup/UpgradeData.php
rmdir  ./app/code/Wyomind/CronScheduler/Model/ResourceModel/Task
rmdir  ./app/code/Wyomind/Watchlog/Block/Adminhtml/System/Config
rmdir  ./app/code/Wyomind/CronScheduler/Controller/Adminhtml/Job
rm ./app/code/Wyomind/SimpleGoogleShopping/Setup/InstallData.php
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/TaskListing
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror5
rm ./app/code/Wyomind/Watchlog/view/adminhtml/web/css/system.css
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/Attributes.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Logger/LoggerCron.php
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component/JobListing
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js/codemirror
rmdir  ./app/code/Wyomind/Watchlog/Controller/Adminhtml/History
rm ./app/code/Wyomind/Watchlog/Controller/Adminhtml/History.php
rm ./app/code/Wyomind/Core/Controller/Activation/Webservice.php
rmdir  ./app/code/Wyomind/Watchlog/Model/ResourceModel/Attempts
rm ./app/code/Wyomind/Core/Console/Command/License/Activate.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Controller/Feeds.php
rm ./app/code/Wyomind/Watchlog/Model/ResourceModel/Attempts.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Controller/Feeds
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/web/css
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Console/Command
rm ./app/code/Wyomind/Core/Console/Command/License/Request.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block/Adminhtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Setup/Recurring.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/Functions.php
rm ./app/code/Wyomind/Watchlog/Controller/Adminhtml/Report.php
rmdir  ./app/code/Wyomind/Watchlog/Controller/Adminhtml/Report
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view/adminhtml
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/web/js
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/layout
rm ./app/code/Wyomind/Core/Console/Command/License/Status.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Logger/Handler.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/Observer.php
rm ./app/code/Wyomind/CronScheduler/etc/adminhtml/system.xml
rm ./app/code/Wyomind/CronScheduler/etc/adminhtml/routes.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/Logger/Logger.php
rmdir  ./app/code/Wyomind/CronScheduler/Plugin/Cron/Observer
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System/Config
rmdir  ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Task
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/etc/adminhtml
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/Parser.php
rmdir  ./app/code/Wyomind/CronScheduler/Console/Command/Task
rm ./app/code/Wyomind/Core/view/adminhtml/web/css/system.css
rmdir  ./app/code/Wyomind/CronScheduler/Controller/Adminhtml
rmdir  ./app/code/Wyomind/Watchlog/Block/Adminhtml/Attempts
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model/Config
rmdir  ./app/code/Wyomind/CronScheduler/Console/Command/Job
rm ./app/code/Wyomind/Core/Model/ResourceModel/Schedule.php
rm ./app/code/Wyomind/CronScheduler/Setup/InstallSchema.php
rmdir  ./app/code/Wyomind/Watchlog/view/adminhtml/templates
rmdir  ./app/code/Wyomind/CronScheduler/Block/Adminhtml/Job
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/etc/frontend
rm ./app/code/Wyomind/SimpleGoogleShopping/registration.php
rmdir  ./app/code/Wyomind/CronScheduler/Model/ResourceModel
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/crontab.xml
rm ./app/code/Wyomind/CronScheduler/etc/adminhtml/menu.xml
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/data/Google
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml/web
rm ./app/code/Wyomind/SimpleGoogleShopping/Helper/Data.php
rm ./app/code/Wyomind/SimpleGoogleShopping/Model/Feeds.php
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/config.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/module.xml
rm ./app/code/Wyomind/SimpleGoogleShopping/i18n/en_US.csv
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Controller
rmdir  ./app/code/Wyomind/Watchlog/Block/Adminhtml/System
rmdir  ./app/code/Wyomind/Watchlog/view/adminhtml/web/css
rm ./app/code/Wyomind/Core/Model/ResourceModel/Config.php
rm ./app/code/Wyomind/SimpleGoogleShopping/i18n/fr_FR.csv
rm ./app/code/Wyomind/Core/Plugin/Config/Model/Config.php
rm ./app/code/Wyomind/SimpleGoogleShopping/composer.json
rm ./app/code/Wyomind/Watchlog/Cron/PeriodicalReport.php
rm ./app/code/Wyomind/Watchlog/Block/Adminhtml/Chart.php
rmdir  ./app/code/Wyomind/Watchlog/view/adminhtml/layout
rm ./app/code/Wyomind/CronScheduler/Helper/HeartBeat.php
rmdir  ./app/code/Wyomind/CronScheduler/Block/Adminhtml
rmdir  ./app/code/Wyomind/Watchlog/Controller/Adminhtml
rm ./app/code/Wyomind/Watchlog/etc/adminhtml/routes.xml
rm ./app/code/Wyomind/Watchlog/etc/adminhtml/system.xml
rmdir  ./app/code/Wyomind/Watchlog/view/adminhtml/email
rmdir  ./app/code/Wyomind/CronScheduler/Ui/DataProvider
rmdir  ./app/code/Wyomind/CronScheduler/Console/Command
rm ./app/code/Wyomind/CronScheduler/Setup/Recurring.php
rm ./app/code/Wyomind/CronScheduler/etc/cron_groups.xml
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Console
rmdir  ./app/code/Wyomind/Core/Console/Command/License
rmdir  ./app/code/Wyomind/Watchlog/Model/ResourceModel
rm ./app/code/Wyomind/Watchlog/Setup/InstallSchema.php
rmdir  ./app/code/Wyomind/Core/view/frontend/templates
rm ./app/code/Wyomind/CronScheduler/Cron/HeartBeat.php
rm ./app/code/Wyomind/Watchlog/etc/email_templates.xml
rmdir  ./app/code/Wyomind/CronScheduler/view/adminhtml
rm ./app/code/Wyomind/SimpleGoogleShopping/LICENSE.TXT
rm ./app/code/Wyomind/Watchlog/Setup/UpgradeSchema.php
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/acl.xml
rm ./app/code/Wyomind/Watchlog/Logger/HandlerCron.php
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml/System
rm ./app/code/Wyomind/Watchlog/etc/adminhtml/menu.xml
rmdir  ./app/code/Wyomind/Watchlog/view/adminhtml/web
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Helper
rm ./app/code/Wyomind/SimpleGoogleShopping/etc/di.xml
rmdir  ./app/code/Wyomind/CronScheduler/etc/adminhtml
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Logger
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/css
rmdir  ./app/code/Wyomind/CronScheduler/Ui/Component
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Setup
rmdir  ./app/code/Wyomind/Core/view/adminhtml/layout
rm ./app/code/Wyomind/Watchlog/Setup/InstallData.php
rm ./app/code/Wyomind/Watchlog/Setup/UpgradeData.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Block
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web/js
rm ./app/code/Wyomind/CronScheduler/registration.php
rm ./app/code/Wyomind/Watchlog/Logger/LoggerCron.php
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/Model
rmdir  ./app/code/Wyomind/Core/Controller/Activation
rm ./app/code/Wyomind/Watchlog/etc/adminhtml/di.xml
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/i18n
rmdir  ./app/code/Wyomind/Core/view/frontend/layout
rmdir  ./app/code/Wyomind/CronScheduler/Plugin/Cron
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/data
rm ./app/code/Wyomind/Core/etc/adminhtml/events.xml
rm ./app/code/Wyomind/CronScheduler/Helper/Task.php
rm ./app/code/Wyomind/Core/etc/adminhtml/system.xml
rm ./app/code/Wyomind/CronScheduler/etc/crontab.xml
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/view
rmdir  ./app/code/Wyomind/SimpleGoogleShopping/etc
rm ./app/code/Wyomind/CronScheduler/etc/module.xml
rm ./app/code/Wyomind/Core/etc/frontend/routes.xml
rmdir  ./app/code/Wyomind/CronScheduler/Controller
rm ./app/code/Wyomind/CronScheduler/Helper/Url.php
rm ./app/code/Wyomind/Core/Model/Notifications.php
rm ./app/code/Wyomind/CronScheduler/i18n/fr_FR.csv
rm ./app/code/Wyomind/CronScheduler/i18n/en_US.csv
rmdir  ./app/code/Wyomind/Core/Model/ResourceModel
rm ./app/code/Wyomind/CronScheduler/Helper/Job.php
rmdir  ./app/code/Wyomind/Core/Plugin/Config/Model
rmdir  ./app/code/Wyomind/Watchlog/Block/Adminhtml
rm ./app/code/Wyomind/CronScheduler/etc/config.xml
rm ./app/code/Wyomind/Watchlog/Model/Attempts.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml/web
rm ./app/code/Wyomind/CronScheduler/composer.json
rmdir  ./app/code/Wyomind/Watchlog/view/adminhtml
rmdir  ./app/code/Wyomind/Watchlog/etc/adminhtml
rm ./app/code/Wyomind/Watchlog/registration.php
rm ./app/code/Wyomind/CronScheduler/LICENSE.TXT
rm ./app/code/Wyomind/Watchlog/Cron/History.php
rmdir  ./app/code/Wyomind/CronScheduler/Console
rm ./app/code/Wyomind/Core/Block/Webservice.php
rm ./app/code/Wyomind/CronScheduler/etc/acl.xml
rm ./app/code/Wyomind/Core/etc/adminhtml/di.xml
rmdir  ./app/code/Wyomind/CronScheduler/Plugin
rmdir  ./app/code/Wyomind/Core/Block/Adminhtml
rm ./app/code/Wyomind/Watchlog/etc/crontab.xml
rmdir  ./app/code/Wyomind/SimpleGoogleShopping
rm ./app/code/Wyomind/CronScheduler/etc/di.xml
rmdir  ./app/code/Wyomind/CronScheduler/Helper
rmdir  ./app/code/Wyomind/Core/Console/Command
rm ./app/code/Wyomind/Watchlog/Helper/Data.php
rmdir  ./app/code/Wyomind/CronScheduler/Setup
rmdir  ./app/code/Wyomind/CronScheduler/Block
rmdir  ./app/code/Wyomind/CronScheduler/Model
rmdir  ./app/code/Wyomind/Watchlog/Controller
rm ./app/code/Wyomind/Core/Logger/Handler.php
rm ./app/code/Wyomind/Core/Helper/License.php
rmdir  ./app/code/Wyomind/Core/view/adminhtml
rm ./app/code/Wyomind/Watchlog/Model/Auth.php
rm ./app/code/Wyomind/Watchlog/etc/module.xml
rm ./app/code/Wyomind/Watchlog/etc/config.xml
rm ./app/code/Wyomind/Core/Logger/Logger.php
rmdir  ./app/code/Wyomind/Core/etc/adminhtml
rmdir  ./app/code/Wyomind/Core/view/frontend
rmdir  ./app/code/Wyomind/CronScheduler/view
rmdir  ./app/code/Wyomind/Core/Plugin/Config
rm ./app/code/Wyomind/Watchlog/composer.json
rmdir  ./app/code/Wyomind/CronScheduler/i18n
rmdir  ./app/code/Wyomind/CronScheduler/Cron
rmdir  ./app/code/Wyomind/CronScheduler/etc
rm ./app/code/Wyomind/Core/registration.php
rmdir  ./app/code/Wyomind/Core/etc/frontend
rm ./app/code/Wyomind/Watchlog/LICENSE.TXT
rmdir  ./app/code/Wyomind/CronScheduler/Ui
rm ./app/code/Wyomind/Core/Helper/Core.php
rm ./app/code/Wyomind/Core/Helper/Data.php
rm ./app/code/Wyomind/Watchlog/etc/acl.xml
rmdir  ./app/code/Wyomind/Watchlog/Logger
rmdir  ./app/code/Wyomind/Core/Controller
rm ./app/code/Wyomind/Core/Model/Feed.php
rm ./app/code/Wyomind/Watchlog/etc/di.xml
rmdir  ./app/code/Wyomind/Watchlog/Helper
rm ./app/code/Wyomind/Core/etc/config.xml
rm ./app/code/Wyomind/Core/etc/module.xml
rm ./app/code/Wyomind/Core/composer.json
rmdir  ./app/code/Wyomind/Watchlog/Model
rmdir  ./app/code/Wyomind/Watchlog/Setup
rmdir  ./app/code/Wyomind/Watchlog/Block
rmdir  ./app/code/Wyomind/Core/Observer
rmdir  ./app/code/Wyomind/Watchlog/Cron
rmdir  ./app/code/Wyomind/CronScheduler
rmdir  ./app/code/Wyomind/Watchlog/view
rm ./app/code/Wyomind/Core/LICENSE.TXT
rmdir  ./app/code/Wyomind/Core/Console
rmdir  ./app/code/Wyomind/Watchlog/etc
rmdir  ./app/code/Wyomind/Core/Helper
rmdir  ./app/code/Wyomind/Core/Logger
rmdir  ./app/code/Wyomind/Core/Plugin
rm ./app/code/Wyomind/Core/etc/di.xml
rmdir  ./app/code/Wyomind/Core/Block
rmdir  ./app/code/Wyomind/Core/Model
rmdir  ./app/code/Wyomind/Core/view
rmdir  ./app/code/Wyomind/Watchlog
rmdir  ./app/code/Wyomind/Core/etc
rmdir  ./app/code/Wyomind/Core
rmdir  ./app/code/Wyomind
rmdir  ./app/code
rmdir  ./app