<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-container"></div>
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                <input type="hidden"
                       class="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>  product bundle option"
                       name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                       value="<?= /* @escapeNotVerified */ $_selections[0]->getSelectionId() ?>"/>
            <?php else:?>
                <?php $i=1; foreach($_selections as $_selection): ?>
                    <div class="field choice">
                        <input class="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?> checkbox product bundle option change-container-classname"
                               id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>"
                               type="checkbox" checked="checked" style="display:none"
                               <?php if ($_option->getRequired() && $i==1) /* @escapeNotVerified */ echo 'data-validate="{\'validate-one-required-by-name\':\'input[name^=&quot;bundle_option[' . $_option->getId() . ']&quot;]:checked\'}"'?>
                               name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>][<?= /* @escapeNotVerified */ $_selection->getId() ?>]"
                               data-selector="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>][<?= /* @escapeNotVerified */ $_selection->getId() ?>]"
                               <?php if ($block->isSelected($_selection) || $i==1) echo ' checked="checked"' ?>
                               <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>
                               value="<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>"/>
                        <label class="label"
                               for="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>">
                            <span><span class="product-name">
                             <?= /* @escapeNotVerified */ $_selection->getSelectionQty() * 1 . ' x ' . $this->escapeHtml($_selection->getName()) ?></span></span>
                    </div>
                <?php $i++; endforeach; ?>              
            <?php endif; ?>
        </div>
    </div>
</div>

<style>
    .bundle-options-container .product-options-wrapper .fieldset > .field:first-of-type{ height:100%; overflow-y: unset;}
    .field-error, div.mage-error[generated]{ position: absolute;}
    .bundle-options-container .product-options-bottom{ margin: 0;}
    .bundle-options-container .block-bundle-summary{margin-top: 0;}
    .page-product-bundle .product-info-main .product-info-price p.price-from{display:none;}
    .page-product-bundle .product-info-main .product-info-price .price-to span.price-label{display:none;}
</style>
