<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<strong class="product name product-item-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?php 
         $productname=$block->escapeHtml($product->getName());
         $strlength=strlen($productname);
        ?>
        <?php if($strlength<56): ?>
            <?= $block->escapeHtml($product->getName()) ?>
        <?php else: ?>
            <?php echo substr($productname,0,50).' ...'; ?>
        <?php endif; ?>  
    </a>
</strong>
