<div class="left_panel">
    <div class="half">
        <div class="product_display">
            <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product1.jpg'); ?>" alt=""></a>
            <h2 class="right button_tran"><a href="#">Quilting</a></h2>
        </div>
        <p class="green_band"><a href="#"><img src="<?php echo $this->getViewFileUrl('images/icon4.png'); ?>" alt=""> Free uk &amp; eu postage options</a></p>                        
    </div>
    <div class="half last">
        <div class="product_display short last">
            <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product2.jpg'); ?>" alt=""></a>
            <h2 class="bottom button_tran"><a href="#">Dressmaking</a></h2>
        </div>
        <p class="green_band"><a href="#"><img src="<?php echo $this->getViewFileUrl('images/icon4.png'); ?>" alt=""> Free uk returns</a></p>
        <div class="product_display short last">
            <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product3.jpg'); ?>" alt=""></a>
            <h2 class="button_tran"><a href="#">Halloween Fabric</a></h2>
        </div>
    </div>
    <div class="product_display">
        <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product5.jpg'); ?>" alt=""></a>
        <h2 class="button_tran"><a href="#">Christmas Fabric</a></h2>
    </div>
</div>
<div class="right_panel">
    <div class="product_display full last">
        <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product4.jpg'); ?>" alt=""></a>
        <h2 class="button_tran"><a href="#">The Haberdashery</a></h2>
    </div>
    <p class="green_band"><a href="#"><img src="<?php echo $this->getViewFileUrl('images/icon4.png'); ?>" alt=""> Same Day Dispatch</a></p>
    <div class="full short_full_panel">
        <div class="product_display half pull-left">
            <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product11.jpg'); ?>" alt=""></a>
            <h2 class="button_tran"><a href="#">Bias Binding</a></h2>
        </div>
        <div class="product_display half pull-right">
            <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product12.jpg'); ?>" alt=""></a>
            <h2 class="button_tran"><a href="#">Threads</a></h2>
        </div>
        <div class="product_display half pull-left">
            <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product13.jpg'); ?>" alt=""></a>
            <h2 class="button_tran"><a href="#">KAM Snaps</a></h2>
        </div>
        <div class="product_display half pull-right">
            <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product14.jpg'); ?>" alt=""></a>
            <h2 class="button_tran"><a href="#">Zips</a></h2>
        </div>
        <div class="product_display half pull-left">
            <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product15.jpg'); ?>" alt=""></a>
            <h2 class="button_tran"><a href="#">Ribbons</a></h2>
        </div>
        <div class="product_display half pull-right">
            <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product16.jpg'); ?>" alt=""></a>
            <h2 class="button_tran"><a href="#">Seissors</a></h2>
        </div>
        <div class="product_display half pull-left">
            <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product17.jpg'); ?>" alt=""></a>
            <h2 class="button_tran"><a href="#">Presing Aids</a></h2>
        </div>
        <div class="product_display half pull-right">
            <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product18.jpg'); ?>" alt=""></a>
            <h2 class="button_tran"><a href="#">Buttons</a></h2>
        </div>
    </div>

    <div class="product_display short full last">
        <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product10.jpg'); ?>" alt=""></a>
        <h2 class="mid button_tran"><a href="#">Sewing Machines</a></h2>
    </div>
</div>
<div class="left_panel">
    <div class="half">
        <div class="half">
            <div class="product_display">
                <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product7.jpg'); ?>" alt=""></a>
                <h2 class="mid center button_tran"><a href="#">New Arrivals</a></h2>
            </div>
        </div>
        <div class="half last">
            <div class="product_display">
                <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product8.jpg'); ?>" alt=""></a>
                <h2 class="mid right button_tran"><a href="#">Visit us</a></h2>
            </div>
            <div class="product_display">
                <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product9.jpg'); ?>" alt=""></a>
                <h2 class="short bottom button_tran"><a href="#">Gift Vouchers</a></h2>
            </div>
        </div>                        
    </div>
    <div class="half last">                        
        <p class="green_band"><a href="#"><img src="<?php echo $this->getViewFileUrl('images/icon4.png'); ?>" alt=""> EARN LOYALTY POINT</a></p>
        <div class="product_display last">
            <a href="#"><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/home-product6.jpg'); ?>" alt=""></a>
            <h2 class="right button_tran"><a href="#">Furnishing</a></h2>
        </div>
    </div>                    
</div>