<div class="owl-carousel">
    <div class="item">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/header1.jpg'); ?>" alt="">
        <div class="info">
        <div class="title_panel"><h2>Half     Price     McCalls     Patterns</h2></div>
        <a href="#" class="button button_tran">Shop Now</a></div>
    </div>
    <div class="item">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/header2.jpg'); ?>" alt="">
        <div class="info">
        <div class="title_panel"><h2>Haberdashery  Patterns in Half  Price</h2></div>
        <a href="#" class="button button_tran">Shop Now</a></div>
    </div>
</div>