<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items" width="650">
        <thead>
            <tr>
                <th class="item-info" align="left" bgcolor="#EAEAEA" style="font-size: 13px;padding: 5px 9px 6px 9px;line-height: 1em;">
                    <?= /* @escapeNotVerified */  __('Items') ?>
                </th>
                <th class="item-qty" align="left" bgcolor="#EAEAEA" style="font-size: 13px;padding: 5px 9px 6px 9px;line-height: 1em;">
                    <?= /* @escapeNotVerified */  __('Sku') ?>
                </th>
                <th class="item-qty" align="center" bgcolor="#EAEAEA" style="font-size: 13px;padding: 5px 9px 6px 9px;line-height: 1em;">
                    <?= /* @escapeNotVerified */  __('Qty') ?>
                </th>
                <th class="item-price" align="right" bgcolor="#EAEAEA" style="font-size: 13px;padding: 5px 9px 6px 9px;line-height: 1em;">
                    <?= /* @escapeNotVerified */  __('Subtotal') ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item): ?>
            <?php
                if ($_item->getParentItem()) {
                    continue;
                }
            ?>
            <tbody bgcolor="#F6F6F6">
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()): ?>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @escapeNotVerified */  __('Gift Message for this Order') ?></h3>
                        <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
