<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Category left navigation
 *
 * @var $block \Magento\Catalog\Block\Navigation
 */
?>
<?php if (!$block->getCategory()) {
    return;
} ?>
<?php $_categories = $block->getCurrentChildCategories(); ?>
<?php $_count = is_array($_categories) ? count($_categories) : $_categories->count(); ?>
<?php if ($_count): ?>
    <div class="block filter">
        <div class="block-content filter-content">
            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
            <div class="filter-options" id="narrow-by-list" data-role="content" role="tablist">
               <div data-role="collapsible" class="filter-options-item allow active" role="presentation" data-collapsible="true">
                  <div data-role="title" class="filter-options-title" role="tab" aria-selected="true" aria-expanded="true" tabindex="0"><?php /* @escapeNotVerified */ echo __('Category') ?></div>
                  <div data-role="content" class="filter-options-content" role="tabpanel" aria-hidden="false" style="display: block;">
                     <ol class="items">   
                        <?php foreach ($_categories as $_category): ?>
                            <?php if ($_category->getIsActive()): ?>
                                <li class="item">
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getCategoryUrl($_category) ?>"<?php if ($block->isCategoryActive($_category)): ?> class="current"<?php endif; ?>><?php echo $block->escapeHtml($_category->getName()) ?></a>
                                    <span class="count"><?php /* @escapeNotVerified */ echo $_category->getProductCount() ?></span>
                                </li>
                            <?php endif; ?>
                        <?php endforeach ?>                                 
                     </ol>
                  </div>
               </div>   
            </div>  
        </div>   
    </div>
 <?php endif; ?>   
