<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrder(); ?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>" style="font-size: 11px; padding: 3px 9px; border-bottom: 1px dotted #cccccc" valign="top" align="left">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl>
                <?php foreach ($block->getItemOptions() as $option): ?>
                    <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                    <dd>
                        <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-info" style="font-size: 11px; padding: 3px 9px; border-bottom: 1px dotted #cccccc" valign="top" align="left"><?= $block->escapeHtml($block->getSku($_item)) ?></td>
    <td class="item-qty" style="font-size: 11px; padding: 3px 9px; border-bottom: 1px dotted #cccccc" valign="top" align="center"><?= /* @escapeNotVerified */  $_item->getQty() * 1 ?></td>
    <td class="item-price" style="font-size: 11px; padding: 3px 9px; border-bottom: 1px dotted #cccccc" valign="top" align="right">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item->getOrderItem()) ?>
    </td>
</tr>
