<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Template for displaying grouped product price
 */
?>
<?php
$minProduct = $block->getSaleableItem()
    ->getPriceInfo()
    ->getPrice(\Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE)
    ->getMinProduct();

if ($minProduct) {
    $amountRender = $block->getRendererPool()
        ->createAmountRender(
            $minProduct->getPriceInfo()->getPrice('final_price')->getAmount(),
            $minProduct,
            $minProduct->getPriceInfo()->getPrice('final_price'),
            ['include_container' => true]
        );
}
?>
<div class="price-box" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
    <?php if ($minProduct && \Magento\Framework\Pricing\Render::ZONE_ITEM_VIEW != $block->getZone()): ?>
    <p class="minimal-price">
        <span class="price-label"><?= /* @escapeNotVerified */ __('Starting at') ?></span><?= $amountRender->toHtml() ?>
    </p>
    <?php endif ?>
        <?php 
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $_product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
            $currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
            $currencyCode = $currencysymbol->getStore()->getCurrentCurrencyCode();
        ?>
        <?php if ($_product): ?>
            <meta itemprop="price" content="<?= /* @escapeNotVerified */ $minProduct->getPriceInfo()->getPrice('final_price')->getAmount() ?>" />
            <meta itemprop="priceCurrency" content="<?= /* @escapeNotVerified */ $currencyCode ?>" />
            <?php if ($_product->isSaleable()): ?>
                <link itemprop="availability" href="http://schema.org/InStock" />
            <?php else:?>
                <link itemprop="availability" href="http://schema.org/OutOfStock" />
            <?php endif;?>
             <meta itemprop="priceValidUntil" content="<?= date('Y-m-d') ?>" />
            <a href="<?= $_product->getProductUrl();?>" itemprop="url"></a>
        <?php endif ?>    
</div>
